version: '3'

services:
  nats:
    image: 'nats:2.8.1'
    expose:
      - "4222"
    ports:
      - "8222:8222"
    networks:
      - opd-net
    hostname: nats-server
  registration-svc:
    build:
      context: .
      dockerfile: ./docker/registration.dockerfile
    image: registration-service:1.0.0
    restart: always
    ports:
      - "9090:9090"
    networks:
      - opd-net
    external_links:
      - db:db
    depends_on:
      - db
  inspection-svc:
    build:
      context: .
      dockerfile: ./docker/inspection.dockerfile
    image: inspection-service:1.0.0
    restart: always
    ports:
      - "9091:9091"
    networks:
      - opd-net
    external_links:
      - db:db
    depends_on:
      - db
  treatment-svc:
    build:
      context: .
      dockerfile: ./docker/treatment.dockerfile
    image: treatment-service:1.0.0
    restart: always
    ports:
      - "9092:9092"
    networks:
      - opd-net
    external_links:
      - db:db
    depends_on:
      - db
  release-svc:
    build:
      context: .
      dockerfile: ./docker/release.dockerfile
    image: release-service:1.0.0
    restart: always
    ports:
      - "9093:9093"
    networks:
      - opd-net
    external_links:
      - db:db
    depends_on:
      - db
  db:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: Root@1985
      MYSQL_DATABASE: opd_data
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    networks:
      - opd-net
    # hostname: mysql8
    volumes:
      - "./resources/init.sql:/docker-entrypoint-initdb.d/init.sql"
networks:
  opd-net:
    driver: bridge
