version: '3'

services:
  nats:
    image: 'nats:2.8.1'
    expose:
      - "4222"
    ports:
      - "8222:8222"
    networks:
      - disgo-net
    hostname: nats-server
  registration-svc:
    build:
      context: .
      dockerfile: ./docker/registration.dockerfile
    image: registration-service:1.0.0
    restart: always
    ports:
      - "9090:9090"
    networks:
      - disgo-net
    external_links:
      - db:registration-db
    depends_on:
      - registration-db
  inspection-svc:
    build:
      context: .
      dockerfile: ./docker/inspection.dockerfile
    image: inspection-service:1.0.0
    restart: always
    ports:
      - "9091:9091"
    networks:
      - disgo-net
    external_links:
      - db:inspection-db
    depends_on:
      - inspection-db
  treatment-svc:
    build:
      context: .
      dockerfile: ./docker/treatment.dockerfile
    image: treatment-service:1.0.0
    restart: always
    ports:
      - "9092:9092"
    networks:
      - disgo-net
    external_links:
      - db:treatment-db
    depends_on:
      - treatment-db
  release-svc:
    build:
      context: .
      dockerfile: ./docker/release.dockerfile
    image: release-service:1.0.0
    restart: always
    ports:
      - "9093:9093"
    networks:
      - disgo-net
    external_links:
      - db:release-db
    depends_on:
      - release-db
  registration-db:
    container_name: registration-db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: disgo_data
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3392:3306'
    networks:
      - disgo-net
    volumes:
      - "./registration-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql"
  inspection-db:
    container_name: inspection-db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: disgo_data
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3391:3306'
    networks:
      - disgo-net
    volumes:
      - "./inspection-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql"
  treatment-db:
    container_name: treatment-db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: disgo_data
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3393:3306'
    networks:
      - disgo-net
    volumes:
      - "./treatment-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql"
  release-db:
    container_name: release-db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: disgo_data
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    networks:
      - disgo-net
    volumes:
      - "./release-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql"
networks:
  disgo-net:
    driver: bridge
